<?xml version='1.0' encoding='utf-8'?>
<ActionCollection version="2" name="Linework">
  <Actions category="Tools">
    <text>Linework</text>
    <Action name="linework_animate">
      <icon />
      <text>Animate Linework layer…</text>
      <toolTip>Animate Linework layer…</toolTip>
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
    </Action>
    <Action name="linework_blank_frame">
      <icon />
      <text>New Linework frame…</text>
      <toolTip>New Linework frame…</toolTip>
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
    </Action>
    <Action name="linework_duplicate_frame">
      <icon />
      <text>Duplicate Linework frame…</text>
      <toolTip>Duplicate Linework frame…</toolTip>
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
    </Action>
    <Action name="linework_vectorize">
      <icon />
      <text>Vectorize layer in Linework…</text>
      <toolTip>Vectorize layer in Linework…</toolTip>
      <iconText>Vectorize layer in Linework…</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkBrush">
      <icon />
      <text>Linework Brush</text>
      <toolTip>Linework Brush</toolTip>
      <iconText>Linework Brush</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkCurve">
      <icon />
      <text>Linework Curve</text>
      <toolTip>Linework Curve</toolTip>
      <iconText>Linework Curve</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkLine">
      <icon />
      <text>Linework Line</text>
      <toolTip>Linework Line</toolTip>
      <iconText>Linework Line</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkEdit">
      <icon />
      <text>Linework Edit</text>
      <toolTip>Linework Edit</toolTip>
      <iconText>Linework Edit</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkPressure">
      <icon />
      <text>Linework Thickness</text>
      <toolTip>Linework Thickness</toolTip>
      <iconText>Linework Thickness</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
    <Action name="LineworkErase">
      <icon />
      <text>Linework Erase</text>
      <toolTip>Linework Erase</toolTip>
      <iconText>Linework Erase</iconText>
      <whatsThis />
      <shortcut />
      <isCheckable>false</isCheckable>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <statusTip />
    </Action>
  </Actions>
</ActionCollection>